-- Create sequences
CREATE SEQUENCE fname_seq START WITH 78 INCREMENT BY 1;
CREATE SEQUENCE lname_seq START WITH 67 INCREMENT BY 1;
CREATE SEQUENCE person_seq START WITH 78 INCREMENT BY 1;
CREATE SEQUENCE person_fname_seq START WITH 78 INCREMENT BY 1;
CREATE SEQUENCE person_lname_seq START WITH 78 INCREMENT BY 1;
CREATE SEQUENCE actor_seq START WITH 56 INCREMENT BY 1;
CREATE SEQUENCE director_seq START WITH 23 INCREMENT BY 1;
